### ISSUE TITLE
Crackling

### ISSUE THREAD

**Issue by Ghostbird** [fugalh/hearnet#2]
https://drive.google.com/open?id=1qws221sAQLA3mqLU6Ei9QJjNg3NYEotF

Demonstrates that there is quite bit of crackling in the synthesis. Which is kind of a shame.

**Comment by fugalh** [comment]
I'm pleasantly surprised it still compiles and runs! I took a look at the code and It looks like younger me was not handling clipping very gracefully (lines 89-96), so it might be that (try adjusting the overall gain so it doesn't clip at all, if that seems to be the issue). Or the decay cutoff is currently about -60dB maybe it should be -70dB (line 106).

If I were to redo this, I would use a wavetable (or wav file input so you could use your own grains), and add a parameter for adjusting gain so if your network is particularly loud you could avoid clipping. Maybe add a compressor or limiter as another way to avoid clipping.

And put in that memory barrier on line 155 (c++17 probably has something standard now).

But probably the biggest flaw here is that all grains start on an audio block boundary, and that will probably be at least 10ms and maybe as much as a couple hundred ms. That won't give you anywhere near a realtime (even time-delayed) sense of the network; it would sound interesting but it sounds *more* interesting if it's sample-accurate. cf Granny which is also not perfected but at least it tries to be sample accurate.

**Comment by Ghostbird** [comment]
I had a look at the code, and I would have liked to make it a MIDI jack output instead, so the user can attach a MIDI instrument, or worse (e.g. autotune your voice to your network adapter). However, I do not have the required knowledge of the Jack API and MIDI, nor do I currently have the time to spend learning it.
I still thought this was a cool piece of software.
It doesn't _sound_ like clipping, but I'm not sure.

**Comment by Ghostbird** [comment]
Actually I ran into the _problematic_ recording today, and played it, and realised there was almost no crackling at all. It must have been an issue with the end-stage of my audio set-up at that time.

**Comment by fugalh** [comment]
Glad to hear it. Thanks for following up
